name: first-workflow
on: workflow_dispatch
jobs:
    first_job:
      runs-on: ubuntu-latest
      steps:
        - name: Print Greating
          run: echo "Hello First Job"
        - name: Print Bye
          run: echo "Done.. Bye!"
      
    
